### ISSUE TITLE
Allow passing summary objectives through the tags

### ISSUE THREAD

**Issue by colega** [cabify/gotoprom#20]
Prometheus removed the default 0.5, 0.9 and 0.95 summary objectives in the `v1.0.0`, so now the summaries this library builds have no objectives at all, and act like an histogram with no buckets (only a sum and a count are exposed).

We should add the ability of providing those objectives through the tags of the summary when it's defined.

**Comment by Mapno** [comment]
Problem addressed in https://github.com/cabify/gotoprom/pull/24. Marking the issue as done.
